// ============================================================
// ShowPilot — Tools → Announcements
// ============================================================
// Turns a voice (generated by lib/tts-engines.js, or an uploaded
// recording) into either:
//
//   • a CLIP — its own MP3 ("Tune your radio", donation asks…), loudness-
//     matched to the songs (default -14 LUFS, same as the normalizer), with
//     optional silence before/after. Goes into an FPP playlist as a
//     media-only entry.
//   • an INTRO — the voice mixed over the opening of a song, with the music
//     ducked underneath. The song keeps its exact length, sample rate and
//     format, so its sequence stays in sync. Never prepends anything —
//     that would shift every effect.
//
// How the intro mix works (one ffmpeg pass):
//   music:  volume envelope in 64-sample steps — ramps down `duck` dB over
//           0.35 s before the voice, holds, ramps back over 0.9 s after.
//   voice:  converted to the song's rate/channels first, then measured, so
//           its gain puts it at the song's loudness (+ voiceBoost).
//   mix:    amix duration=first (length = the song's), normalize=0, then a
//           4x-oversampled look-ahead limiter at the peak ceiling.
//   check:  decoded sample count of the result must equal the original's.
//
// Everything here is on demand and in os.tmpdir()/showpilot-announcer
// (cleared on start, entries expire 3 h after last use). One job at a time.
// ============================================================
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const norm = require('./audio-normalizer');
const tts = require('./tts-engines');

const WORK = path.join(os.tmpdir(), 'showpilot-announcer');
const TTL_MS = 3 * 60 * 60 * 1000;
const PEAK_CEILING = -1.5;
const MAX_UPLOAD = 300 * 1024 * 1024;

const voices = new Map();
const songs = new Map();
const outputs = new Map();
const jobs = new Map();
const queue = [];
let running = null;

const newId = () => crypto.randomBytes(8).toString('hex');
const r1 = (n) => Math.round(n * 10) / 10;
const r3 = (n) => Math.round(n * 1000) / 1000;

function start() {
  try { fs.rmSync(WORK, { recursive: true, force: true }); } catch (_) {}
  fs.mkdirSync(WORK, { recursive: true });
  setInterval(sweep, 10 * 60 * 1000).unref();
}

function sweep() {
  const now = Date.now();
  for (const map of [voices, songs, outputs]) {
    for (const [id, v] of map) {
      if (now - v.touchedAt > TTL_MS) {
        for (const f of [v.file, v.mp3, v.src].concat(v.prepped ? Object.values(v.prepped) : [])) {
          if (f) try { fs.rmSync(f, { force: true }); } catch (_) {}
        }
        map.delete(id);
      }
    }
  }
  for (const [id, j] of jobs) if (now - j.updatedAt > TTL_MS && j.status !== 'running') jobs.delete(id);
}

function touch(x) { if (x) x.touchedAt = Date.now(); return x; }

// ------------------------------------------------------------
// Jobs
// ------------------------------------------------------------
function addJob(type, fn) {
  const j = { id: newId(), type, status: 'queued', step: 'Waiting…', result: null, error: null, createdAt: Date.now(), updatedAt: Date.now() };
  jobs.set(j.id, j);
  queue.push({ j, fn });
  setImmediate(pump);
  return j;
}
async function pump() {
  if (running || !queue.length) return;
  const { j, fn } = queue.shift();
  running = j;
  j.status = 'running';
  j.updatedAt = Date.now();
  try {
    j.result = await fn((step) => { j.step = step; j.updatedAt = Date.now(); });
    j.status = 'done';
    j.step = null;
  } catch (e) {
    j.status = 'error';
    j.error = String(e && e.message || e);
  } finally {
    j.updatedAt = Date.now();
    running = null;
    setImmediate(pump);
  }
}
function getJob(id) {
  const j = jobs.get(String(id || ''));
  if (!j) return null;
  const pos = queue.findIndex(q => q.j.id === j.id);
  return { id: j.id, type: j.type, status: j.status, step: j.step, error: j.error, result: j.result, queuePosition: pos >= 0 ? pos + 1 : null };
}

// ------------------------------------------------------------
// Voices
// ------------------------------------------------------------
async function registerVoice(file, meta) {
  const info = await norm.probe(file);
  const m = await norm.measure(file);
  const duration = m.samples ? m.samples / info.sampleRate : info.duration;
  if (duration < 0.2) throw new Error('The voice clip is empty');
  const v = { id: path.basename(file, '.wav'), file, duration, loud: { i: m.i, tp: m.tp }, prepped: {}, touchedAt: Date.now() };
  Object.assign(v, meta);
  voices.set(v.id, v);
  return publicVoice(v);
}
function publicVoice(v) {
  return { id: v.id, duration: r3(v.duration), text: v.text || null, engine: v.engine || null, uploadedName: v.uploadedName || null };
}

function generateVoice(engine, text, opts) {
  return addJob('voice', async (step) => {
    step(engine === 'kokoro' ? 'Speaking (free voice on this server — can take a little while)…' : 'Asking ' + (engine === 'openai' ? 'OpenAI' : 'ElevenLabs') + ' for the voice…');
    const id = newId();
    const file = path.join(WORK, id + '.wav');
    const res = await tts.synthesize(engine, text, opts, file);
    step('Checking the voice…');
    rememberScript(engine, text, opts);
    return registerVoice(file, { text: String(text).trim(), engine: res.engine });
  });
}

async function receiveFile(req, dest) {
  return new Promise((resolve, reject) => {
    let bytes = 0;
    const ws = fs.createWriteStream(dest);
    req.on('data', (c) => {
      bytes += c.length;
      if (bytes > MAX_UPLOAD) { req.unpipe(ws); ws.destroy(); req.resume(); reject(new Error('File is too large')); }
    });
    req.pipe(ws);
    req.on('error', reject);
    ws.on('error', reject);
    ws.on('finish', () => (bytes > 0 ? resolve(bytes) : reject(new Error('Empty file'))));
  });
}

async function uploadVoice(req, name) {
  const id = newId();
  const src = path.join(WORK, id + '.upload' + path.extname(name).toLowerCase());
  await receiveFile(req, src);
  return addJob('voice', async (step) => {
    step('Reading your recording…');
    const file = path.join(WORK, id + '.wav');
    try { await tts.toWav(src, file); } finally { fs.rmSync(src, { force: true }); }
    return registerVoice(file, { uploadedName: name, engine: 'uploaded recording' });
  });
}

async function voiceMp3(id) {
  const v = touch(voices.get(id));
  if (!v) return null;
  if (!v.mp3) {
    const mp3 = v.file.replace(/\.wav$/, '.preview.mp3');
    const r = await norm.run(norm.FFMPEG, ['-hide_banner', '-nostats', '-y', '-i', v.file, '-c:a', 'libmp3lame', '-b:a', '160k', mp3], { timeoutMs: 120000 });
    if (r.code !== 0) throw new Error('Could not make a preview');
    v.mp3 = mp3;
  }
  return v.mp3;
}

// Voice converted to a target rate/channel count and measured there (a
// mono voice played on two channels measures 3 LU louder, so measure the
// version that will actually be mixed).
async function preppedVoice(v, sampleRate, channels) {
  const key = sampleRate + 'x' + channels;
  if (v.prepped[key] && fs.existsSync(v.prepped[key].file)) return v.prepped[key];
  const file = v.file.replace(/\.wav$/, '.' + key + '.wav');
  const r = await norm.run(norm.FFMPEG, ['-hide_banner', '-nostats', '-y', '-i', v.file,
    '-af', 'highpass=f=70', '-ar', String(sampleRate), '-ac', String(channels), '-c:a', 'pcm_f32le', file], { timeoutMs: 300000 });
  if (r.code !== 0) throw new Error('Could not prepare the voice (' + norm.lastLine(r.stderr) + ')');
  const m = await norm.measure(file);
  const p = { file, i: m.i, tp: m.tp, duration: m.samples ? m.samples / sampleRate : v.duration };
  v.prepped[key] = p;
  return p;
}

// ------------------------------------------------------------
// Songs (for intros)
// ------------------------------------------------------------
async function registerSong(id, file, name, source, step) {
  step('Measuring the song…');
  const info = await norm.probe(file);
  const m = await norm.measure(file);
  const s = {
    id, name, source, file, info, ext: path.extname(name).toLowerCase(),
    samples: m.samples, duration: m.samples ? m.samples / info.sampleRate : info.duration,
    loud: { i: m.i, tp: m.tp }, touchedAt: Date.now(),
  };
  songs.set(id, s);
  return publicSong(s);
}
function publicSong(s) {
  return { id: s.id, name: s.name, source: s.source, duration: r3(s.duration), loudness: r1(s.loud.i), sampleRate: s.info.sampleRate, channels: s.info.channels };
}

function songFromFpp(host, name) {
  return addJob('song', async (step) => {
    if (!norm.FORMATS[path.extname(name).toLowerCase()]) throw new Error('Unsupported file type');
    step('Getting the song from FPP…');
    const id = newId();
    const file = path.join(WORK, id + '.song' + path.extname(name).toLowerCase());
    await norm.downloadFromFpp(host, name, file);
    return registerSong(id, file, name, 'fpp', step);
  });
}

async function uploadSong(req, name) {
  const id = newId();
  const file = path.join(WORK, id + '.song' + path.extname(name).toLowerCase());
  await receiveFile(req, file);
  return addJob('song', (step) => registerSong(id, file, name, 'upload', step));
}

// ------------------------------------------------------------
// Rendering
// ------------------------------------------------------------
function limiterChain(sampleRate, tools) {
  const lin = Math.pow(10, (PEAK_CEILING - 0.5) / 20).toFixed(5);
  if (!tools.alimiter) return null;
  return 'aresample=' + (sampleRate * 4) + ',alimiter=limit=' + lin + ':attack=5:release=50:level=false' +
    (tools.limiterLatency ? ':latency=true' : '') + ',aresample=' + sampleRate;
}

function layoutFor(ch) { return ch === 1 ? 'mono' : ch === 2 ? 'stereo' : null; }

function renderClip(o) {
  return addJob('clip', async (step) => {
    const v = touch(voices.get(o.voiceId));
    if (!v) throw new Error('That voice has expired — generate it again');
    const name = norm.safeMediaName(o.name);
    if (!name || name.includes('/') || path.extname(name).toLowerCase() !== '.mp3') throw new Error('File name must end in .mp3 (no folders)');
    const target = clampNum(o.targetLufs, -30, -5, -14);
    const leadIn = clampNum(o.leadIn, 0, 10, 0.5);
    const tail = clampNum(o.tail, 0, 30, 1);
    const tools = await norm.checkTools();
    step('Building the clip…');
    const p = await preppedVoice(v, 44100, 2);
    const gain = r1(target - p.i);
    const chain = ['volume=' + gain.toFixed(2) + 'dB'];
    if (leadIn > 0) chain.push('adelay=delays=' + Math.round(leadIn * 1000) + ':all=1');
    if (tail > 0) chain.push('apad=pad_dur=' + tail);
    const lim = limiterChain(44100, tools);
    if (lim) chain.push(lim);
    const id = newId();
    const file = path.join(WORK, id + '.out.mp3');
    const title = name.replace(/\.mp3$/i, '');
    const r = await norm.run(norm.FFMPEG, ['-hide_banner', '-nostats', '-threads', '1', '-y', '-i', p.file,
      '-af', chain.join(','), '-ar', '44100', '-ac', '2', '-c:a', 'libmp3lame', '-b:a', '320k',
      '-id3v2_version', '3', '-write_xing', '1', '-metadata', 'title=' + title, '-metadata', 'artist=Announcement', file]);
    if (r.code !== 0) throw new Error('Building the clip failed (' + norm.lastLine(r.stderr) + ')');
    step('Checking the result…');
    const m = await norm.measure(file);
    const out = { id, kind: 'clip', name, file, ext: '.mp3', size: fs.statSync(file).size, duration: m.samples / 44100, loud: { i: m.i, tp: m.tp }, voiceId: v.id, touchedAt: Date.now() };
    outputs.set(id, out);
    return publicOutput(out);
  });
}

function clampNum(v, lo, hi, dflt) {
  const n = Number(v);
  if (!Number.isFinite(n)) return dflt;
  return Math.min(hi, Math.max(lo, n));
}

function renderIntro(o) {
  return addJob(o.preview ? 'intro-preview' : 'intro', async (step) => {
    const v = touch(voices.get(o.voiceId));
    if (!v) throw new Error('That voice has expired — generate it again');
    const s = touch(songs.get(o.songId));
    if (!s) throw new Error('That song has expired — load it again');
    const fmt = norm.FORMATS[s.ext];
    if (!fmt) throw new Error('Unsupported song format');
    const tools = await norm.checkTools();
    if (!tools.encoders[s.ext]) throw new Error('This ffmpeg can\'t write ' + s.ext + ' files');
    const sr = s.info.sampleRate;
    const ch = s.info.channels;
    const startAt = clampNum(o.start, 0, 600, 1);
    const duck = clampNum(o.duckDb, 0, 30, 12);
    const boost = clampNum(o.voiceBoost, -10, 10, 0);

    step('Preparing the voice…');
    const p = await preppedVoice(v, sr, ch);
    const end = startAt + p.duration;
    if (end + 0.5 > s.duration) throw new Error('The voice runs past the end of the song — start it earlier or shorten it');
    const gain = r1(s.loud.i + boost - p.i);

    const F = 0.35, R = 0.9;
    const env = '-' + duck + '*min(clip((t-' + (startAt - F).toFixed(3) + ')/' + F + ',0,1),clip((' + (end + R).toFixed(3) + '-t)/' + R + ',0,1))';
    const musicChain = 'asetnsamples=n=64:p=0,volume=eval=frame:volume=\'pow(10,(' + env + ')/20)\'';
    const layout = layoutFor(ch);
    const voiceChain = 'aresample=' + sr + (layout ? ',aformat=channel_layouts=' + layout : '') +
      ',volume=' + gain.toFixed(2) + 'dB,adelay=delays=' + Math.round(startAt * 1000) + ':all=1';
    const lim = limiterChain(sr, tools);
    const graph = '[0:a:0]' + musicChain + '[m];[1:a:0]' + voiceChain + '[v];' +
      '[m][v]amix=inputs=2:duration=first:dropout_transition=0:normalize=0' + (lim ? ',' + lim : '') + '[out]';

    const id = newId();
    const base = ['-hide_banner', '-nostats', '-threads', '1', '-y', '-i', s.file, '-i', p.file, '-filter_complex', graph];
    if (o.preview) {
      step('Making a preview…');
      const from = Math.max(0, startAt - 2);
      const len = Math.min(s.duration - from, end + 4 - from);
      const file = path.join(WORK, id + '.preview.mp3');
      const r = await norm.run(norm.FFMPEG, base.concat(['-map', '[out]', '-ss', from.toFixed(3), '-t', len.toFixed(3), '-c:a', 'libmp3lame', '-b:a', '192k', file]));
      if (r.code !== 0) throw new Error('Making the preview failed (' + norm.lastLine(r.stderr) + ')');
      const out = { id, kind: 'preview', name: 'preview.mp3', file, ext: '.mp3', size: fs.statSync(file).size, duration: len, touchedAt: Date.now() };
      outputs.set(id, out);
      return publicOutput(out);
    }

    step('Mixing the full song…');
    const file = path.join(WORK, id + '.out' + s.ext);
    const tail = ['-ar', String(sr), '-ac', String(ch)].concat(fmt.codec, ['-map_metadata', '0']);
    if (fmt.id3) tail.push('-id3v2_version', '3', '-write_xing', '1');
    tail.push('-f', fmt.muxer, file);
    const withArt = fmt.art && s.info.hasArt;
    let r = await norm.run(norm.FFMPEG, base.concat(['-map', '[out]'], withArt ? ['-map', '0:v:0', '-c:v', 'copy', '-disposition:v:0', 'attached_pic'] : [], tail));
    if (r.code !== 0 && withArt) r = await norm.run(norm.FFMPEG, base.concat(['-map', '[out]'], tail));
    if (r.code !== 0) throw new Error('Mixing failed (' + norm.lastLine(r.stderr) + ')');

    step('Checking the length…');
    const m = await norm.measure(file);
    const diffMs = (m.samples != null && s.samples != null) ? Math.round((m.samples - s.samples) / sr * 1000) : null;
    const out = {
      id, kind: 'intro', name: s.name, file, ext: s.ext, size: fs.statSync(file).size,
      duration: m.samples ? m.samples / sr : null, lengthDiffMs: diffMs, loud: { i: m.i, tp: m.tp },
      songId: s.id, voiceId: v.id, songSource: s.source, touchedAt: Date.now(),
    };
    outputs.set(id, out);
    return publicOutput(out);
  });
}

function publicOutput(o) {
  return {
    id: o.id, kind: o.kind, name: o.name, size: o.size, duration: o.duration == null ? null : r3(o.duration),
    lengthDiffMs: o.lengthDiffMs == null ? null : o.lengthDiffMs,
    loudness: o.loud ? r1(o.loud.i) : null, peak: o.loud ? r1(o.loud.tp) : null,
    songId: o.songId || null, sent: o.sent || null,
  };
}

function getOutput(id) { return touch(outputs.get(String(id || ''))) || null; }

async function sendOutput(host, id, name) {
  const o = getOutput(id);
  if (!o || o.kind === 'preview') throw new Error('Nothing to send');
  const n = norm.safeMediaName(name || o.name);
  if (!n || n.includes('/')) throw new Error('Pick a file name without folders');
  if (path.extname(n).toLowerCase() !== o.ext) throw new Error('Keep the ' + o.ext + ' extension');
  await norm.uploadToFpp(host, n, o.file);
  o.sent = n;
  return publicOutput(o);
}

async function restoreSong(host, songId) {
  const s = touch(songs.get(String(songId || '')));
  if (!s) throw new Error('The original has expired');
  if (s.name.includes('/')) throw new Error('This song is in a sub-folder on FPP');
  await norm.uploadToFpp(host, s.name, s.file);
  return true;
}

// ------------------------------------------------------------
// Recent scripts (data/tts/library.json)
// ------------------------------------------------------------
function libFile() { return path.join(tts.ttsDir(), 'library.json'); }
function recentScripts() {
  try { return JSON.parse(fs.readFileSync(libFile(), 'utf8')).slice(0, 30); } catch (_) { return []; }
}
function rememberScript(engine, text, opts) {
  const list = recentScripts().filter(x => x.text !== String(text).trim());
  list.unshift({ text: String(text).trim().slice(0, 2000), engine, voice: (opts && (opts.voiceName || opts.voice)) || null, at: new Date().toISOString() });
  try { fs.writeFileSync(libFile(), JSON.stringify(list.slice(0, 30), null, 2)); } catch (_) {}
}
function forgetScript(text) {
  const list = recentScripts().filter(x => x.text !== String(text || '').trim());
  try { fs.writeFileSync(libFile(), JSON.stringify(list, null, 2)); } catch (_) {}
}

module.exports = {
  start, getJob, generateVoice, uploadVoice, voiceMp3, songFromFpp, uploadSong,
  renderClip, renderIntro, getOutput, sendOutput, restoreSong, recentScripts, forgetScript,
  publicSong, _internal: { voices, songs, outputs },
};
